### ISSUE TITLE
Please create a gentoo ebuild.

### ISSUE THREAD

**Issue by aTosser** [kbumsik/VirtScreen#24]
I attempted to clone and run on gentoo but your instal method with setup.py does not detect the system installed PyQt5. I do not wish to have another installation of PyQt5 on my machine (from pip).
Can you please either have the setup.py search for the system PyQt or create a gentoo ebuild that respects the system?

**Comment by kbumsik** [comment]
Hi,
the first thing you can try is the AppImage package that can be found in our release page. While the size of the file is big because it is self-contained, this is a single executable file that does not install nothing in your system.

If you still want setup.py or ebuild, could you tell me about your machine? Since I have never used Gentoo before and installing using pip on my Arch Linux machine works, I would need the following to resolve the problem:

1. The output of `pip install .` , including both normal messages and the error message.
2. The output of `python3 -c "import PyQt5; print(PyQt5);"`

**Comment by kbumsik** [comment]
I close this issue due to inactivity. Please feel to reopen it if someone still needs a gentoo ebuild.

**Comment by hedmo** [comment]
i like to have an ebuild for gentoo and i am happy to help you out . but i need to know how to manually install it and the deps..it is not recommended to use pip in gentoo.pip will install stuff outside portage (the package manager) and can make conflicts later on. 

regards hedmo

**Comment by aTosser** [comment]
I just threw one together but I am having an issue with the tray icon not appearing, I will continue to try to hammer one out to get it working then maybe @kbumsik can submit it to the gentoo repo.

If you want to try to roll your own the deps I have discovered are:

dev-python/PyQt5
dev-python/PyQt5-sip
dev-python/netifaces
dev-python/quamash  (which I had to write an ebuild for)
x11-misc/x11vnc  (this may need a useflag or two)

Please let me know if I overlooked a dep, but I would like to know what other capabilities are required from x11vnc (xinerama support??)

**Comment by hedmo** [comment]
can you post the ebuild?

**Comment by aTosser** [comment]
I have not had time to work out the issues. Still a work in progress. Does not work as of yet. 
[virtscreen-ebuilds.tar.gz](https://github.com/kbumsik/VirtScreen/files/3744595/virtscreen-ebuilds.tar.gz)

 I placed virtscreen in app-misc as there was no category that really seemed to apply. (maybe x11-misc)

**Comment by lquenti** [comment]
@aTosser your quamash ebuild seems broken, at least not readable. Any more work done yet?

**Comment by hedmo** [comment]
@lquenti you can  try it here if you like to : https://github.com/hedmo/hedmos-overlay
give me feedback if there is more deps to add to the ebuild

regards
